### ISSUE TITLE
Tests fail with latest Zope security fix

### ISSUE THREAD

**Issue by mauritsvanrees** [plone/plone.app.caching#106]
On Jenkins, both [5.2 Py3](https://jenkins.plone.org/job/plone-5.2-python-3.8/1512/testReport/) and [6.0](https://jenkins.plone.org/job/plone-6.0-python-3.11/302/testReport/) fail like this:

```
Failure in test test_composite_viewsxx (plone.app.caching.tests.test_profile_with_caching_proxy.TestProfileWithCaching.test_composite_viewsxx)
Traceback (most recent call last):
  File "/Users/maurits/.pyenv/versions/3.11.0/lib/python3.11/unittest/case.py", line 57, in testPartExecutor
    yield
  File "/Users/maurits/.pyenv/versions/3.11.0/lib/python3.11/unittest/case.py", line 623, in run
    self._callTestMethod(testMethod)
  File "/Users/maurits/.pyenv/versions/3.11.0/lib/python3.11/unittest/case.py", line 579, in _callTestMethod
    if method() is not None:
  File "/Users/maurits/community/plone-coredev/6.0/src/plone.app.caching/plone/app/caching/tests/test_profile_with_caching_proxy.py", line 202, in test_composite_viewsxx
    self.assertEqual("", browser.contents)
  File "/Users/maurits/.pyenv/versions/3.11.0/lib/python3.11/unittest/case.py", line 873, in assertEqual
    assertion_func(first, second, msg=msg)
  File "/Users/maurits/.pyenv/versions/3.11.0/lib/python3.11/unittest/case.py", line 866, in _baseAssertEqual
    raise self.failureException(msg)
AssertionError: '' != b''
```

So we used to get an empty byte, and now we get an empty string (Python 3).
I don't know which part of the security fix does this.
I guess we don't care, as long as it is empty. If someone knows a reason that we *should* care, please speak up.
Meanwhile I am working on PRs.

**Comment by mauritsvanrees** [comment]
Fixes have been released.
